# Generated by Django 4.2.4 on 2023-08-23 15:39

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PurePosixPath('/home/alexander/FlowerShop/media/bouquets'), verbose_name='фото')),
                ('price', models.FloatField(verbose_name='цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='имя')),
                ('phone', models.CharField(max_length=300, verbose_name='телефон')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
                ('period', models.TimeField(choices=[(1, 'Как можно скорее'), (2, 'с 10:00 до 12:00'), (3, 'с 12:00 до 14:00'), (4, 'с 14:00 до 16:00'), (5, 'с 16:00 до 18:00'), (6, 'с 18:00 до 20:00')], default=1, verbose_name='время доставки')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.bouquet', verbose_name='букет')),
            ],
        ),
    ]
