# Generated by Django 4.2.4 on 2023-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='media/bouquets', verbose_name='фото'),
        ),
    ]
