# Generated by Django 4.2.4 on 2023-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_bouquet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Как можно скорее'), (2, 'с 10:00 до 12:00'), (3, 'с 12:00 до 14:00'), (4, 'с 14:00 до 16:00'), (5, 'с 16:00 до 18:00'), (6, 'с 18:00 до 20:00')], default=1, verbose_name='время доставки'),
        ),
    ]
