# Generated by Django 4.2.4 on 2023-08-24 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Название букета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
