# Generated by Django 4.2.4 on 2023-08-25 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_bouquet_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер карты')),
                ('month', models.PositiveSmallIntegerField(verbose_name='месяц окончания действия карты')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год окончания действия карты')),
                ('name', models.CharField(max_length=300, verbose_name='имя владельца карты')),
                ('cvc', models.PositiveSmallIntegerField(verbose_name='cvc карты')),
                ('mail', models.CharField(default=None, max_length=100, verbose_name='e-mail')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='shop.order', verbose_name='заказ который надо оплатить')),
            ],
        ),
    ]
