# Generated by Django 4.2.4 on 2023-08-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Интервал')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.timeinterval', verbose_name='временной интервал'),
        ),
    ]
