# Generated by Django 4.2.4 on 2023-08-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_timeinterval_alter_order_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aviso',
        ),
    ]
